### ISSUE TITLE
MaxSourceMetadata conflict resolution policy not supported? 

### ISSUE THREAD

**Issue by tomas-knap** [mifeet/FusionTool-DPU#1]
When I executed uv-t-fusion DPU with the config containing: 

```
<DefaultStrategy function="MaxSourceMetadata" cardinality="SINGLEVALUED" aggregationErrorStrategy="RETURN_ALL" />
```

i got: 

```
Execution failed because: cz.cuni.mff.odcleanstore.conflictresolution.exceptions.ResolutionFunctionNotRegisteredException: Resolution function identified by 'MaxSourceMetadata' is not registeredeu.unifiedviews.plugins.transformer.fusiontool.exceptions.FusionToolDpuException: cz.cuni.mff.odcleanstore.conflictresolution.exceptions.ResolutionFunctionNotRegisteredException: Resolution function identified by 'MaxSourceMetadata' is not registered
at eu.unifiedviews.plugins.transformer.fusiontool.FusionToolDpu.handleException(FusionToolDpu.java:168)
at eu.unifiedviews.plugins.transformer.fusiontool.FusionToolDpu.execute(FusionToolDpu.java:138)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.executeInstance(DPUExecutor.java:232)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.execute(DPUExecutor.java:370)
at cz.cuni.mff.xrg.odcs.backend.execution.dpu.DPUExecutor.run(DPUExecutor.java:452)
at java.lang.Thread.run(Thread.java:745)
Caused by: cz.cuni.mff.odcleanstore.conflictresolution.exceptions.ResolutionFunctionNotRegisteredException: Resolution function identified by 'MaxSourceMetadata' is not registered
at cz.cuni.mff.odcleanstore.conflictresolution.impl.ResolutionFunctionRegistryImpl.get(ResolutionFunctionRegistryImpl.java:24)
at cz.cuni.mff.odcleanstore.fusiontool.conflictresolution.impl.ResourceDescriptionConflictResolverImpl.getResolutionFunction(ResourceDescriptionConflictResolverImpl.java:305)
at cz.cuni.mff.odcleanstore.fusiontool.conflictresolution.impl.ResourceDescriptionConflictResolverImpl.resolveConflictCluster(ResourceDescriptionConflictResolverImpl.java:268)
at cz.cuni.mff.odcleanstore.fusiontool.conflictresolution.impl.ResourceDescriptionConflictResolverImpl.resolveResource(ResourceDescriptionConflictResolverImpl.java:153)
at cz.cuni.mff.odcleanstore.fusiontool.conflictresolution.impl.ResourceDescriptionConflictResolverImpl.resolveConflicts(ResourceDescriptionConflictResolverImpl.java:105)
at cz.cuni.mff.odcleanstore.fusiontool.LDFusionToolExecutor.fuse(LDFusionToolExecutor.java:92)
at cz.cuni.mff.odcleanstore.fusiontool.FusionRunner.runFusionTool(FusionRunner.java:78)
at eu.unifiedviews.plugins.transformer.fusiontool.FusionToolDpu.execute(FusionToolDpu.java:132)
... 4 more
```

So it seems that MaxSourceMetadata is not supported?  I took the name for the CRP from http://arxiv.org/pdf/1410.7990v1.pdf

Tested on develop: 735965d326367211816665ce4f5e7aefe66f74c4

**Comment by tomas-knap** [comment]
Answer is enough, no need to implement now

**Comment by feynmanix** [comment]
Please try using "MAX_SOURCE_METADATA" instead of "MaxSourceMetadata". I cannot find this properly documented, but you can refer to ConflictResolverFactory for the list of all available functions.
